### ISSUE TITLE
Allow configuring custom just executable path

### ISSUE THREAD

**Issue by stijndcl** [linux-china/jetbrains-just-plugin#37]
It would be nice if it were possible to manually configure the path of the `just` executable in the settings, like the JetBrains JS/TS and Python plugins do as well. This way I can point to my `just` binary myself. In my case, it's not (always) available as `just` on my system PATH.

Currently, trying to run a Run Configuration fails instantly because the plugin cannot find the executable. If I could tell it where to look, this problem would not exist.

**Comment by linux-china** [comment]
@stijndcl could you supply `just` install path on your desktop/laptop?   Because just is a simple CLI and most developers added it in system PATH.  I'm not sure that an UI configuration is necessary or not.   Maybe I should have a test on Windows platform.

**Comment by stijndcl** [comment]
@linux-china I manage my project using [`devenv`](https://devenv.sh/), which means it is not globally installed. It gets added to my PATH automatically whenever I `cd` into my project directory in my terminal, which the plugin (obviously) does not do.

The `just` executable itself gets symlinked to `{PROJECT ROOT}/.devenv/profile/bin/just` and resides somewhere else in a cache directory. If you don't want to add a setting for it then maybe support the project-relative devenv path instead?

**Comment by linux-china** [comment]
@stijndcl  for your case, it's project based,  and still boring to set just executable path for every project.  
No worry, and I will add devenv support.  

-  Locate the justfile's directory
- try to find just from `project_root_dir/.devenv/profile/bin/just`

**Comment by linux-china** [comment]
Fixed on version 0.6.7.

**Comment by linux-china** [comment]
Add devenv and homebrew support with version 0.6.7

**Comment by stijndcl** [comment]
This seems to work when opening the justfile and running a recipe from the gutter, but not when using run configs. Run configs still give me `just: command not found`. Problem with the first approach is that it doesn't allow passing arguments to recipes (as far as I'm aware?) so this doesn't resolve the issue for me.

**Comment by stijndcl** [comment]
Thanks!
